db.restaurants.find()
db.restaurants.find({}, {restaurant_id:1, name: 1, borough: 1,  cuisine: 1})
db.restaurants.find({}, {restaurant_id:1, name: 1, borough: 1,  cuisine: 1, _id: 0})
db.restaurants.find({}, {restaurant_id:1 , name: 1, borough: 1,  "address.zipcode": 1,  _id: 0})
db.restaurants.find({borough: "Bronx"}).pretty()
db.restaurants.find({borough: "Bronx"}).limit(5)
db.restaurants.find({borough: "Bronx"}).skip(5).limit(5)
db.restaurants.find({"grades.score": {"$gt": 90}})
db.restaurants.find({"grades": {$elemMatch: {"score": {$gt: 80 , $lt: 100 }}}})
db.restaurants.find({"address.coord.0": {"$lt": -95.754168}})
db.restaurants.find({"$and": [{"grades.score": {"$gt": 70}}, {"address.coord.0": {"$lt":-65.754168}},{"cuisine" : {$ne : "American "}}]})
db.restaurants.find({"cuisine" : {$ne : "American "}, "grades.score" :{$gt: 70}, "address.coord.1" : {$lt:-65.754168}})
db.restaurants.find({"$and": [{"grades.grade": "A"}, {"cuisine" : {$ne : "American "}}, {"borough": {$ne:"Brooklyn"}}]}).sort({cuisine: -1})
db.restaurants.find({"name" : {$regex: '^Wil.*'}}, {"_id": 0,"restaurant_id":  1,"name":  1, "borough": 1, "cuisine": 1})
db.restaurants.find({"name" : {$regex: '.*ces$'}}, {"_id": 0,"restaurant_id":  1,"name":  1, "borough": 1, "cuisine": 1})
db.restaurants.find({"name" : {$regex: 'Reg'}}, {"_id": 0,"restaurant_id":  1,"name":  1, "borough": 1, "cuisine": 1})
db.restaurants.find({"borough": "Bronx", "cuisine": {$in:["American ", "Chinese"]}}, {_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine:1})
db.restaurants.find({"borough": {$in:["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine:1})
db.restaurants.find({"borough": {$nin:["Staten Island", "Queens", "Bronx", "Brooklyn"]}}, {_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine:1})
db.restaurants.find({"grades.score": {$lt: 10}}, {_id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine:1})
db.restaurants.find({$nor:[{"name": {$regex: '^Wil.*'}}, {"cuisine": {$in: ["American ","Chinese"]}},  {"cuisine": {$not: {$in: ["Seafood"]}}}]}, {"_id": 0,"restaurant_id": 1,"name": 1, "borough": 1, "cuisine": 1})
db.restaurants.find({"grades" : {$elemMatch: {"date": ISODate("2014-08-11T00:00:00Z"), "grade": "A", "score": 11}}}, {_id: 0, restaurant_id: 1, name: 1, grades: 1})
db.restaurants.find({$and : [{"grades.1.date": ISODate("2014-08-11T00:00:00Z")}, {"grades.1.grade": "A"}, {"grades.1.score": 9}]}, {_id: 0, restaurant_id: 1, name: 1, grades: 1})
db.restaurants.find({$and : [{"address.coord.1": {$gte: 42}}, {"address.coord.1": {$lte: 52}}]}, {_id: 0, restaurant_id: 1, name: 1, address: 1})
db.restaurants.find({}, {_id: 0, name: 1}).sort({name: 1})
db.restaurants.find({}, {_id: 0, name: 1}).sort({name: -1})
db.restaurants.find({}, {_id: 0, cuisine: 1, borough: 1}).sort({cuisine: 1, borough: -1})
db.restaurants.find({"address.street": {$exists: "Street"}})
db.restaurants.find({"address.coord": {$type: "double"}})
db.restaurants.find({"grades": {$elemMatch: {"score": {$mod: [7, 0]}}}}, {_id: 0, restaurant_id: 1, name: 1, grade: 1})
db.restaurants.find({name: {$regex: 'mon'}}, {_id: 0, name: 1, borough: 1, "address.coord": 1, cuisine: 1})
db.restaurants.find({name: {$regex: '^Mad.*'}}, {_id: 0, name: 1, borough: 1, "address.coord": 1, cuisine: 1})
